### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [raghvendra-v/tosca-yaml-lsp#2]
Hello TOSCA DSL team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the TOSCA DSL project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>
```

We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by raghvendra-v** [comment]
<tr>
	<td><a href="https://github.com/raghvendra-v/tosca-yaml-lsp">TOSCA DSL</a></td>
	<td>IDE framework to develop and test <a href="https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=tosca">tosca</a> templates. works with eclipse, Idea and LSP </td>
	<td>GPL-3.0</td>
	<td>Eclipse IDE, Language</td>
	<td>raghvendra @ <a href="https://www.bt.com/">BT</a></td>
</tr>
